# Replica count for the database deployment
replicaCount: 1

# name of resources such as statefulset, container, service
name: database

# Image repository and tag for the database container
image:
  repository: mongo
  tag: latest

# Port for the database service
servicePort: 27017