apiVersion: v1
kind: Namespace
metadata:
  name: nodejs
  namespace: nodejs
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: nodejs
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      # nodePort: 30002 # Node Port
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: nodejs
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 480566855108.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

