apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: be-image=480566855108.dkr.ecr.us-east-1.amazonaws.com/backend:latest
    argocd-image-updater.argoproj.io/be-image.update-strategy: digest
    argocd-image-updater.argoproj.io/be-image.pull-secret: secret:argocd/aws-ecr-creds#creds
  name: backend-auto-sync
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/charts/backend
    repoURL: https://github.com/Chau-NH/helm-charts.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - {{ .Values.valuesFile }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated: 
      prune: true 
      selfHeal: true 