apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/charts/mongodb
    repoURL: https://github.com/Chau-NH/helm-charts.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - {{ .Values.valuesFile }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated: 
      prune: true 
      selfHeal: true 