apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "app.label" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      {{- include "app.label" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.label" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.servicePort }}
  strategy:
    blueGreen: 
      activeService: {{ .Values.name }}
      previewService: {{ .Values.namePreview }}
      autoPromotionEnabled: false
