apiVersion: v1
kind: Namespace
metadata:
  name: nodejs
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: nodejs
spec:
  selector:
    app: backend
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      # nodePort: 30001 # Node Port

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: nodejs
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 480566855108.dkr.ecr.us-east-1.amazonaws.com/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000