apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nodejs-monitor
  # Change this to the namespace the Prometheus instance is running in
  namespace: nodejs
  labels:
    app: backend
spec:
  endpoints:
  - path: /metrics
    interval: 15s
    scheme: http
  namespaceSelector:
    matchNames:
    - nodejs
  selector:
    matchLabels:
      app: backend
