apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "app.label" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: {{ .Values.servicePort }}
      protocol: {{ .Values.serviceProtocol }}
  selector:
    {{- include "app.label" . | nindent 4 }}

